Description: DevOps Demo Kubernetes Cluster
Parameters:
  EnvironmentName:
    Description: Name of the environment
    Type: String
Resources:
  EKSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvironmentName}-eks-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-vpc"
  Cluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub "${EnvironmentName}-cluster"
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroup
        SubnetIds:
          - Fn::ImportValue:
              !Sub "${EnvironmentName}-private-subnet-1"
          - Fn::ImportValue:
              !Sub "${EnvironmentName}-private-subnet-2"
      RoleArn: !GetAtt EKSRole.Arn
      Tags:
        - Key: Project
          Value: !Sub "${EnvironmentName}"
    DependsOn:
      - EKSRole
      - SecurityGroup
Outputs:
  ClusterSecurityGroup:
    Description: A reference to security group of the cluster
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}-cluster-sg
  DedicatedClusterSecurityGroup:
    Description: A reference to security group of the cluster
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}-cluster-dedicated-sg
  ClusterName:
    Description: Name of the cluster
    Value: !Ref Cluster
    Export:
      Name: !Sub ${EnvironmentName}-cluster-name
