Description: DevOps Demo Security
Parameters:
  EnvironmentName:
    Description: Name of the environment
    Type: String
Resources:
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Sub "${EnvironmentName}-key"
      KeyType: rsa
  EKSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvironmentName}-eks-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

Outputs:
  EKSRole:
    Description: A reference to the EKS Role
    Value: !Ref EKSRole
    Export:
      Name: !Sub ${EnvironmentName}-eks-role
