Description: DevOps Demo Security
Parameters:
  EnvironmentName:
    Description: Name of the environment
    Type: String
Resources:
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Sub "${EnvironmentName}-key"
      KeyType: rsa
